u21503193_HW03/Models/borrows.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace u21503193_HW03.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class borrows
    {
        public int borrowId { get; set; }
        public Nullable<int> studentId { get; set; }
        public Nullable<int> bookId { get; set; }
        public Nullable<System.DateTime> takenDate { get; set; }
        public Nullable<System.DateTime> broughtDate { get; set; }
    
        public virtual books books { get; set; }
        public virtual students students { get; set; }
    }
}

u21503193_HW03/Controllers/MaintainController.cs
using PagedList.EntityFramework;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using u21503193_HW03.Models;

namespace u21503193_HW03.Controllers
{
    public class MaintainController : Controller
    {
        LibraryEntities db = new LibraryEntities();

        public async Task<ActionResult> Index(int? authorPage, int? typePage, int? borrowPage)
        {
            int pageSize = 10;

            int authorPageNumber = authorPage ?? 1;
            int typePageNumber = typePage ?? 1;
            int borrowPageNumber = borrowPage ?? 1;

            var authors = await db.authors.OrderBy(a => a.authorId).ToPagedListAsync(authorPageNumber, pageSize);
            var types = await db.types.OrderBy(t => t.typeId).ToPagedListAsync(typePageNumber, pageSize);
            var borrows = await db.borrows.OrderBy(b => b.borrowId).ToPagedListAsync(borrowPageNumber, pageSize);

            var viewModel = new CombinedReportVM
            {
                Authors = authors,
                Types = types,
                Borrows = borrows
            };

            return View(viewModel);
        }
    }
}

u21503193_HW03/Controllers/borrowsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using u21503193_HW03.Models;

namespace u21503193_HW03.Controllers
{
    public class borrowsController : Controller
    {
        private LibraryEntities db = new LibraryEntities();

        // GET: borrows
        public async Task<ActionResult> Index()
        {
            var borrows = db.borrows.Include(b => b.books).Include(b => b.students);
            return View(await borrows.ToListAsync());
        }

        // GET: borrows/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            borrows borrows = await db.borrows.FindAsync(id);
            if (borrows == null)
            {
                return HttpNotFound();
            }
            return View(borrows);
        }

        // GET: borrows/Create
        public ActionResult Create()
        {
            ViewBag.bookId = new SelectList(db.books, "bookId", "name");
            ViewBag.studentId = new SelectList(db.students, "studentId", "name");
            return View();
        }

        // POST: borrows/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "borrowId,studentId,bookId,takenDate,broughtDate")] borrows borrows)
        {
            if (ModelState.IsValid)
            {
                db.borrows.Add(borrows);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            ViewBag.bookId = new SelectList(db.books, "bookId", "name", borrows.bookId);
            ViewBag.studentId = new SelectList(db.students, "studentId", "name", borrows.studentId);
            return View(borrows);
        }

        // GET: borrows/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            borrows borrows = await db.borrows.FindAsync(id);
            if (borrows == null)
            {
                return HttpNotFound();
            }
            ViewBag.bookId = new SelectList(db.books, "bookId", "name", borrows.bookId);
            ViewBag.studentId = new SelectList(db.students, "studentId", "name", borrows.studentId);
            return View(borrows);
        }

        // POST: borrows/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "borrowId,studentId,bookId,takenDate,broughtDate")] borrows borrows)
        {
            if (ModelState.IsValid)
            {
                db.Entry(borrows).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewBag.bookId = new SelectList(db.books, "bookId", "name", borrows.bookId);
            ViewBag.studentId = new SelectList(db.students, "studentId", "name", borrows.studentId);
            return View(borrows);
        }

        // GET: borrows/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            borrows borrows = await db.borrows.FindAsync(id);
            if (borrows == null)
            {
                return HttpNotFound();
            }
            return View(borrows);
        }

        // POST: borrows/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            borrows borrows = await db.borrows.FindAsync(id);
            db.borrows.Remove(borrows);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

u21503193_HW03/Views/borrows/Create.cshtml
@model u21503193_HW03.Models.borrows

@{
    Layout = null;
}

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Borrows</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.studentId, "studentId", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("studentId", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.studentId, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.bookId, "bookId", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("bookId", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.bookId, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.takenDate, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.takenDate, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.takenDate, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.broughtDate, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.broughtDate, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.broughtDate, "", new { @class = "text-danger" })
        </div>
    </div>
    <br />
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <a href="@Url.Action("Index", "Maintain")" class="btn btn-primary btn-sm">Back to List</a>
            <input type="submit" value="Create" class="btn btn-primary btn-sm" />
        </div>
    </div>
</div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

u21503193_HW03/Views/borrows/Delete.cshtml
@model u21503193_HW03.Models.borrows

@{
    Layout = null;
}

<h3>Are you sure you want to delete this borrow record?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.takenDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.takenDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.broughtDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.broughtDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.books.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.books.name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.students.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.students.name)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-primary btn-sm" /> |
            <a href="@Url.Action("Index", "Maintain")" class="btn btn-primary btn-sm">Back to List</a>
        </div>
    }
</div>

u21503193_HW03/Views/borrows/Details.cshtml
@model u21503193_HW03.Models.borrows

@{
    Layout = null;
}

<div>
    <h4>Borrows</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.takenDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.takenDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.broughtDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.broughtDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.books.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.books.name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.students.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.students.name)
        </dd>

    </dl>
</div>
<p>
    <a href="@Url.Action("Index", "Maintain")" class="btn btn-primary btn-sm">Back to List</a>
</p>

u21503193_HW03/Views/borrows/Edit.cshtml
@model u21503193_HW03.Models.borrows

@{
    Layout = null;
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Borrows</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.borrowId)

    <div class="form-group">
        @Html.LabelFor(model => model.studentId, "studentId", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("studentId", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.studentId, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.bookId, "bookId", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("bookId", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.bookId, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.takenDate, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.takenDate, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.takenDate, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.broughtDate, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.broughtDate, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.broughtDate, "", new { @class = "text-danger" })
        </div>
    </div>
    <br />
    <div class="form-group">

        <div class="col-md-offset-2 col-md-10">
            <a href="@Url.Action("Index", "Maintain")" class="btn btn-primary btn-sm">Back to List</a>
            <input type="submit" value="Save" class="btn btn-primary btn-sm" />
        </div>
    </div>
</div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

u21503193_HW03/Views/borrows/Index.cshtml
@model IEnumerable<u21503193_HW03.Models.borrows>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.takenDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.broughtDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.books.name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.students.name)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.takenDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.broughtDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.books.name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.students.name)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.borrowId }) |
            @Html.ActionLink("Details", "Details", new { id=item.borrowId }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.borrowId })
        </td>
    </tr>
}

</table>