u21503193_HW03/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using u21503193_HW03.Models;
using PagedList;
using System.Web.UI;
using PagedList.EntityFramework;

namespace u21503193_HW03.Controllers
{
    public class HomeController : Controller
    {
        LibraryEntities db = new LibraryEntities();

        public async Task<ActionResult> Index(int? studentPage, int? bookPage)
        {
            int pageSize = 10;

            int studentPageNumber = studentPage ?? 1;
            int bookPageNumber = bookPage ?? 1;

            var students = await db.students.OrderBy(s => s.studentId).ToPagedListAsync(studentPageNumber, pageSize);
            var books = await db.books.OrderBy(b => b.bookId).ToPagedListAsync(bookPageNumber, pageSize);
            var borrows = await db.borrows.ToListAsync();

            foreach (var book in books)
            {
                var borrowRecord = borrows.FirstOrDefault(b => b.bookId == book.bookId && b.broughtDate == null);
                if (borrowRecord != null)
                {
                    book.BookStatus = Status.Out;
                }
                else
                {
                    book.BookStatus = Status.Available;
                }
            }

            var viewModel = new CombinedHomeVM
            {
                Students = students,
                Books = books
            };

            return View(viewModel);
        }

        // GET: students
        public async Task<ActionResult> studentsIndex()
        {
            return View(await db.students.ToListAsync());
        }

        // GET: students/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: students/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> studentsCreate([Bind(Include = "studentId,name,surname,birthdate,gender,class,point")] students students)
        {
            if (ModelState.IsValid)
            {
                db.students.Add(students);
                await db.SaveChangesAsync();
                return RedirectToAction("studentsIndex");
            }

            return View(students);
        }

        // GET: books
        public async Task<ActionResult> booksIndex()
        {
            var books = db.books.Include(b => b.authors).Include(b => b.types);
            return View(await books.ToListAsync());
        }

        // GET: books/Create
        public ActionResult booksCreate()
        {
            ViewBag.authorId = new SelectList(db.authors, "authorId", "name");
            ViewBag.typeId = new SelectList(db.types, "typeId", "name");
            return View();
        }

        // POST: books/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> booksCreate([Bind(Include = "bookId,name,pagecount,point,authorId,typeId")] books books)
        {
            if (ModelState.IsValid)
            {
                db.books.Add(books);
                await db.SaveChangesAsync();
                return RedirectToAction("booksIndex");
            }

            ViewBag.authorId = new SelectList(db.authors, "authorId", "name", books.authorId);
            ViewBag.typeId = new SelectList(db.types, "typeId", "name", books.typeId);
            return View(books);
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

u21503193_HW03/Controllers/booksController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using u21503193_HW03.Models;

namespace u21503193_HW03.Controllers
{
    public class booksController : Controller
    {
        private LibraryEntities db = new LibraryEntities();

        // GET: books
        public async Task<ActionResult> Index()
        {
            var books = db.books.Include(b => b.authors).Include(b => b.types);
            return View(await books.ToListAsync());
        }

        // GET: books/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            books books = await db.books.FindAsync(id);
            if (books == null)
            {
                return HttpNotFound();
            }
            return View(books);
        }

        // GET: books/Create
        public ActionResult Create()
        {
            ViewBag.authorId = new SelectList(db.authors, "authorId", "name");
            ViewBag.typeId = new SelectList(db.types, "typeId", "name");
            return View();
        }

        // POST: books/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "bookId,name,pagecount,point,authorId,typeId")] books books)
        {
            if (ModelState.IsValid)
            {
                db.books.Add(books);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            ViewBag.authorId = new SelectList(db.authors, "authorId", "name", books.authorId);
            ViewBag.typeId = new SelectList(db.types, "typeId", "name", books.typeId);
            return View(books);
        }

        // GET: books/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            books books = await db.books.FindAsync(id);
            if (books == null)
            {
                return HttpNotFound();
            }
            ViewBag.authorId = new SelectList(db.authors, "authorId", "name", books.authorId);
            ViewBag.typeId = new SelectList(db.types, "typeId", "name", books.typeId);
            return View(books);
        }

        // POST: books/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "bookId,name,pagecount,point,authorId,typeId")] books books)
        {
            if (ModelState.IsValid)
            {
                db.Entry(books).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewBag.authorId = new SelectList(db.authors, "authorId", "name", books.authorId);
            ViewBag.typeId = new SelectList(db.types, "typeId", "name", books.typeId);
            return View(books);
        }

        // GET: books/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            books books = await db.books.FindAsync(id);
            if (books == null)
            {
                return HttpNotFound();
            }
            return View(books);
        }

        // POST: books/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            books books = await db.books.FindAsync(id);
            db.books.Remove(books);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

u21503193_HW03/Controllers/studentsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using u21503193_HW03.Models;

namespace u21503193_HW03.Controllers
{
    public class studentsController : Controller
    {
        private LibraryEntities db = new LibraryEntities();

        // GET: students
        public async Task<ActionResult> Index()
        {
            return View(await db.students.ToListAsync());
        }

        // GET: students/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            students students = await db.students.FindAsync(id);
            if (students == null)
            {
                return HttpNotFound();
            }
            return View(students);
        }

        // GET: students/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: students/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "studentId,name,surname,birthdate,gender,class,point")] students students)
        {
            if (ModelState.IsValid)
            {
                db.students.Add(students);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(students);
        }

        // GET: students/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            students students = await db.students.FindAsync(id);
            if (students == null)
            {
                return HttpNotFound();
            }
            return View(students);
        }

        // POST: students/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "studentId,name,surname,birthdate,gender,class,point")] students students)
        {
            if (ModelState.IsValid)
            {
                db.Entry(students).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(students);
        }

        // GET: students/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            students students = await db.students.FindAsync(id);
            if (students == null)
            {
                return HttpNotFound();
            }
            return View(students);
        }

        // POST: students/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            students students = await db.students.FindAsync(id);
            db.students.Remove(students);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

u21503193_HW03/Views/Home/Index.cshtml
@model u21503193_HW03.Models.CombinedHomeVM
@{
    ViewBag.Title = "Index";
}

<link href="~/Content/Site.css" rel="stylesheet" />

<div class="row">

    <div class="header">
        <h1>Welcome to the Library Management System</h1>
    </div>

    <div class="welcome-message">
        <p>This website allows you to manage students and books in the library. You can create, update, and delete student and book records, as well as view them in an organized manner.</p>
    </div>

    <div class="col-md-6">
        <div class="section">
            <div class="row">
                <div class="col-md-6">
                    <h2>Students</h2>
                </div>
                <div class="col-md-6" style="text-align:right">
                    <a href="#" class="create-link btn btn-light btn-outline-primary" data-url="@Url.Action("Create", "students")">Create</a>
                </div>
            </div>

            <table class="table table-striped table-bordered" style="width:100%">
                <thead class="bg-primary" style="color:white">
                    <tr>
                        <th>
                            Name
                        </th>
                        <th>
                            Surname
                        </th>
                        <th>
                            Birthdate
                        </th>
                        <th>
                            Gender
                        </th>
                        <th>
                        Class
                        </th>
                        <th>
                            Point
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var student in Model.Students)
                    {
                        <tr>
                            <td>
                                @student.name
                            </td>
                            <td>
                                @student.surname
                            </td>
                            <td>
                                @student.birthdate
                            </td>
                            <td>
                                @student.gender
                            </td>
                            <td>
                            @(student.@class)
                            </td>
                            <td>
                                @student.point
                            </td>
                        </tr>
                    }
                </tbody>
            </table>

            <ul class="pagination">
                @if (Model.Students.HasPreviousPage)
                {
                    <li class="page-item">
                        <a class="page-link" href="@Url.Action("Index", new { studentPage = Model.Students.PageNumber - 1, bookPage = Model.Books.PageNumber })">Previous</a>
                    </li>
                }

                @if (Model.Students.PageCount <= 7)
                {
                    for (int i = 1; i <= Model.Students.PageCount; i++)
                    {
                        <li class="page-item @(i == Model.Students.PageNumber ? "active" : "")">
                            <a class="page-link" href="@Url.Action("Index", new { studentPage = i, bookPage = Model.Books.PageNumber })">@i</a>
                        </li>
                    }
                }
                else
                {
                    int startPage = Math.Max(1, Model.Students.PageNumber - 2);
                    int endPage = Math.Min(Model.Students.PageCount, Model.Students.PageNumber + 2);

                    if (startPage > 1)
                    {
                        <li class="page-item">
                            <a class="page-link" href="@Url.Action("Index", new { studentPage = 1, bookPage = Model.Books.PageNumber })">1</a>
                        </li>
                        <li class="page-item disabled"><span class="page-link">...</span></li>
                    }

                    for (int i = startPage; i <= endPage; i++)
                    {
                        <li class="page-item @(i == Model.Students.PageNumber ? "active" : "")">
                            <a class="page-link" href="@Url.Action("Index", new { studentPage = i, bookPage = Model.Books.PageNumber })">@i</a>
                        </li>
                    }

                    if (endPage < Model.Students.PageCount)
                    {
                        <li class="page-item disabled"><span class="page-link">...</span></li>
                        <li class="page-item">
                            <a class="page-link" href="@Url.Action("Index", new { studentPage = Model.Students.PageCount, bookPage = Model.Books.PageNumber })">@Model.Students.PageCount</a>
                        </li>
                    }
                }

                @if (Model.Students.HasNextPage)
                {
                    <li class="page-item">
                        <a class="page-link" href="@Url.Action("Index", new { studentPage = Model.Students.PageNumber + 1, bookPage = Model.Books.PageNumber })">Next</a>
                    </li>
                }
            </ul>
        </div>
    </div>

    <div class="col-md-6">
        <div class="section">
            <div class="row">
                <div class="col-md-6">
                    <h2>Books</h2>
                </div>
                <div class="col-md-6" style="text-align:right">
                    <a href="#" class="create-link btn btn-light btn-outline-primary" data-url="@Url.Action("Create", "books")">Create</a>
                </div>
            </div>
                    <table class="table table-striped table-bordered" style="width:100%">
                        <thead class="bg-primary" style="color:white">
                            <tr>
                                <th>
                                    Name
                                </th>
                                <th>
                                    Page Count
                                </th>
                                <th>
                                    Point
                                </th>
                                <th>
                                    Author
                                </th>
                                <th>
                                    Type
                                </th>
                                <th>
                                    Status
                                </th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var books in Model.Books)
                            {
                                <tr>
                                    <td>
                                        @books.name
                                    </td>
                                    <td>
                                        @books.pagecount
                                    </td>
                                    <td>
                                        @books.point
                                    </td>
                                    <td>
                                        @books.authors.name
                                    </td>
                                    <td>
                                        @books.types.name
                                    </td>
                                    <td>
                                        @books.BookStatus
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>

                    <ul class="pagination">
                        @if (Model.Books.HasPreviousPage)
                        {
                            <li class="page-item">
                                <a class="page-link" href="@Url.Action("Index", new { studentPage = Model.Students.PageNumber, bookPage = Model.Books.PageNumber - 1 })">Previous</a>
                            </li>
                        }

                        @if (Model.Books.PageCount <= 7)
                        {
                            for (int i = 1; i <= Model.Books.PageCount; i++)
                            {
                                <li class="page-item @(i == Model.Books.PageNumber ? "active" : "")">
                                    <a class="page-link" href="@Url.Action("Index", new { studentPage = Model.Students.PageNumber, bookPage = i })">@i</a>
                                </li>
                            }
                        }
                        else
                        {
                            int startPage = Math.Max(1, Model.Books.PageNumber - 2);
                            int endPage = Math.Min(Model.Books.PageCount, Model.Books.PageNumber + 2);

                            if (startPage > 1)
                            {
                                <li class="page-item">
                                    <a class="page-link" href="@Url.Action("Index", new { studentPage = Model.Students.PageNumber, bookPage = 1 })">1</a>
                                </li>
                                <li class="page-item disabled"><span class="page-link">...</span></li>
                            }

                            for (int i = startPage; i <= endPage; i++)
                            {
                                <li class="page-item @(i == Model.Books.PageNumber ? "active" : "")">
                                    <a class="page-link" href="@Url.Action("Index", new { studentPage = Model.Students.PageNumber, bookPage = i })">@i</a>
                                </li>
                            }

                            if (endPage < Model.Books.PageCount)
                            {
                                <li class="page-item disabled"><span class="page-link">...</span></li>
                                <li class="page-item">
                                    <a class="page-link" href="@Url.Action("Index", new { studentPage = Model.Students.PageNumber, bookPage = Model.Books.PageCount })">@Model.Books.PageCount</a>
                                </li>
                            }
                        }

                        @if (Model.Books.HasNextPage)
                        {
                            <li class="page-item">
                                <a class="page-link" href="@Url.Action("Index", new { studentPage = Model.Students.PageNumber, bookPage = Model.Books.PageNumber + 1 })">Next</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
</div>

    <div id="myModal" class="modal fade" tabindex="-1">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body" id="modal-content">
                </div>
            </div>
        </div>
    </div>

    <script>
        $(function () {
            // Function to handle form submission within the modal
            $("#modal-content").on("submit", "form", function (e) {
                e.preventDefault();
                var form = $(this);
                var url = form.attr("action");
                var formData = form.serialize();

                $.post(url, formData, function (data) {
                    $("#myModal").modal("hide");
                    location.reload();
                });
            });

            // Function to handle other links (details, delete, create) within the modal
            $(".create-link").click(function (e) {
                e.preventDefault();
                var url = $(this).data("url");

                $.get(url, function (data) {
                    $("#modal-content").empty();
                    $("#modal-content").html(data);
                    $("#myModal").modal("show");
                });
            });
        });
    </script>